# Generated by Django 3.0.8 on 2020-08-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicketAppItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_name', models.TextField()),
                ('flight_date', models.TextField()),
                ('flight_capacity', models.TextField()),
                ('flight_booked_seats', models.TextField()),
                ('flight_remained_seats', models.TextField()),
                ('flight_price', models.TextField()),
                ('flight_income', models.TextField()),
                ('depart_city', models.TextField()),
                ('arrive_city', models.TextField()),
                ('depart_airport', models.TextField()),
                ('arrive_airport', models.TextField()),
                ('depart_time', models.TextField()),
                ('arrive_time', models.TextField()),
            ],
        ),
    ]
