# Generated by Django 3.0.8 on 2020-08-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketApp', '0003_remove_ticketitem_flight_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTicketItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('flight_id', models.IntegerField()),
                ('book_status', models.TextField()),
            ],
        ),
    ]
