# Generated by Django 3.0.8 on 2020-08-14 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TicketApp', '0004_bookticketitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookticketitem',
            old_name='flight_id',
            new_name='ticket_id',
        ),
    ]
