# Generated by Django 3.0.8 on 2020-08-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketApp', '0006_auto_20200815_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketitem',
            name='flight_booked_seats',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ticketitem',
            name='flight_capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ticketitem',
            name='flight_remained_seats',
            field=models.IntegerField(),
        ),
    ]
