# Generated by Django 3.1.1 on 2020-10-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketApp', '0007_auto_20200815_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookticketitem',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='bookticketitem',
            name='user',
        ),
        migrations.AddField(
            model_name='bookticketitem',
            name='ticket_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookticketitem',
            name='user_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
