# Generated by Django 3.1.1 on 2020-10-24 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_auto_20200805_2149'),
        ('TicketApp', '0008_auto_20201024_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookticketitem',
            name='ticket_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TicketApp.ticketitem'),
        ),
        migrations.AlterField(
            model_name='bookticketitem',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.useritem'),
        ),
    ]
