# Generated by Django 3.1.1 on 2020-10-27 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TicketApp', '0010_auto_20201024_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckinItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_windows', models.TextField()),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TicketApp.ticketitem')),
            ],
        ),
    ]
