# Generated by Django 3.1.1 on 2020-11-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketApp', '0011_checkinitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookticketitem',
            name='seat_id',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
