# Generated by Django 3.1.1 on 2020-11-03 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketApp', '0012_bookticketitem_seat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinitem',
            name='boarding_port',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
