# Generated by Django 3.0.8 on 2020-08-03 14:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userappitem',
            old_name='content',
            new_name='email',
        ),
        migrations.AddField(
            model_name='userappitem',
            name='password',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userappitem',
            name='username',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
