# Generated by Django 3.0.8 on 2020-08-05 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_auto_20200803_2208'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAppItem',
            new_name='UserItem',
        ),
    ]
