# Generated by Django 3.1.1 on 2020-11-03 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_auto_20200805_2149'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserItem',
        ),
    ]
